analytics: {}
color:
  brandColors:
    - '#A8B0D0'
    - '#284870'
    - '#706880'
    - '#1870C0'
    - '#F8B058'
  brandStrength: 1
  lightness: 0.512387
  rhythmicContrast: 0.519144
  saturation: 0.507882
cta: {}
layout_spectrum: 0.5
name: Clay Curtin
opengraph: {}
purpose: []
typography_spectrum: 0.38725545769557357
